### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by rishabhnambiar** [ayushs08/passworld#9]
- [x] Clean code up
- [x] Refer to style guide and format
- [x] Check UX Flow
- [x] Decide and Implement how to involve flavors in generate()
- [x] Add password field
- [x] Documentation
- [x] Mobile-responsive
- [ ] e-mail
